spring.application.name=strike-off-partner-objections-processor

management.endpoint.health.show-details=${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:never}
management.endpoint.health.probes.enabled=${MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED:true}
management.endpoints.web.exposure.include=${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health}
management.endpoints.web.base-path=${MANAGEMENT_ENDPOINTS_WEB_BASE_PATH:/strike-off-partner-objections-processor}
management.endpoints.web.path-mapping.health=${MANAGEMENT_ENDPOINTS_WEB_PATH_MAPPING_HEALTH:healthcheck}
logging.level.org.springframework.kafka=DEBUG
logging.level.org.apache.kafka=INFO
logging.level.org.springframework.kafka.config=DEBUG

spring.kafka.bootstrap-servers=${BOOTSTRAP_SERVER_URL:localhost:29093}

kafka.topic.strikeoff.objections=${KAFKA_TOPIC_STRIKEOFF_OBJECTIONS:strike-off-partner-objections-incoming}
kafka.strikeoff.objections.group-id=${KAFKA_STRIKEOFF_OBJECTIONS_GROUP_ID:strike-off-partner-objections-incoming-consumer}
kafka.session.timeout=${SESSION_TIMEOUT_MS_CONFIG:60000}
kafka.max.poll.interval=${MAX_POLL_INTERVAL_MS_CONFIG:350000}
kafka.heartbeat.interval=${HEARTBEAT_INTERVAL_MS_CONFIG:10000}
kafka.max.poll.records=${MAX_POLL_RECORDS_CONFIG:1}

kafka.max-attempts=${MAX_ATTEMPTS:5}
kafka.backoff-delay=${BACKOFF_DELAY:1000}
kafka.concurrency=${CONCURRENT_LISTENER_INSTANCES:1}