spring.application.name=strike-off-partner-objections-processor

management.endpoint.health.show-details=${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:never}
management.endpoint.health.probes.enabled=${MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED:true}
management.endpoints.web.exposure.include=${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health}
management.endpoints.web.base-path=${MANAGEMENT_ENDPOINTS_WEB_BASE_PATH:/strike-off-partner-objections-processor}
management.endpoints.web.path-mapping.health=${MANAGEMENT_ENDPOINTS_WEB_PATH_MAPPING_HEALTH:healthcheck}

spring.mongodb.uri=${MONGODB_URL}
spring.mongodb.auto-index-creation=${MONGODB_AUTO_INDEX_CREATION:false}

# Spring MongoDB
spring.data.mongodb.field-naming-strategy=org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy